import Head from "next/head"
export default function PageHeader(){
   return( <Head>
        <title>Dellaleaders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
    </Head>
    )
}